nullstone-io/nullstone

.github/workflows/release.yml, cmd/configure.go, config/api_key.go, go.mod, go.sum, main.go
This PR adds the `nullstone configure` CLI command.
This repo has already been configured (not tested yet) with `goreleaser` that will publish to GitHub Releases, Homebrew (mac), and Scoop (windows) from GitHub Actions when a `vx.y.z` tag is pushed.
=> 263 Initial draft of configure command

cmd/configure.go, cmd/flag_org.go, cmd/flag_profile.go, cmd/set_org.go, config/profile.go, main.go
This PR introduces a CLI command, CLI flag, and env var to contextualize commands to a nullstone organization:
- `nullstone --profile=<profile> set-org` - writes a file `~/.nullstone/<profile>/org` that is used for all commands when that profile is in use
- `nullstone --org=<org> ...` flag that overrides the organization to use when running CLI commands
- This flag will use `NULLSTONE_ORG` env var if it exists in the environment
=> 263 Added context-specific organization to CLI

go.mod, go.sum, main.go, outputs/errors.go, outputs/field.go, outputs/field_test.go, outputs/mock_ns.go, outputs/retriever.go, outputs/retriever_test.go, outputs/valid_fields.go
This PR introduces `outputs.Retriever`.
The goal of this struct is to provide a simple, contract-based method for defining outputs in nullstone modules.
This is done through the use of struct tags on `Outputs` struct for each category+module type.
Since the `Retriever` is heavily tested, there is less likelihood of issues introduced when building for other app patterns and module types.
NOTE: I *could* see this going in another repo some day, but I left in the CLI until it becomes an issue.
As an example, the following structs define the outputs needed for performing actions on `aws-fargate-service`.
```
// contracts/aws-fargate-service
type Outputs struct {
ServiceName  string          `ns:"service_name"`
ImageRepoUrl docker.ImageUrl `ns:"image_repo_url,optional"`
ImagePusher  aws.User …
```
=> 291+290 Built outputs retriever using struct tags

app/container/aws-fargate/provider.go, app/serverless/aws-lambda/infra_config.go, app/serverless/aws-lambda/provider.go, cmd/deploy.go, cmd/push.go, contracts/aws-lambda-service/outputs.go, go.mod, go.sum, nullstone/main.go
This PR implements the push/deploy provider for `app/serverless` => `aws-lambda`.
This also removes `--image-tag` CLI flag from `push` command. Instead, uses the `--version` CLI option.
=> 292 Lambda support

app/container/aws-fargate/infra_config.go, contracts/aws-fargate-service/outputs.go
This PR adds support for `main_container_name` output from fargate service.
This enables the CLI to run `deploy` commands when more than 1 container is running in the ECS service.
If the module does not emit `main_container_name` output, the user gets the following error:
```
service contains multiple containers; cannot deploy unless service module exports 'main_container_name'
```
If the `main_container_name` is not in the task definition, the user gets the following error:
```
cannot deploy service; no container definition with main_container_name = <main_container_name>
```
=> Add support for 'main_container_name' output

app/container/aws-fargate/provider.go, app/provider.go, app/serverless/aws-lambda/provider.go, app/update_version.go, cmd/deploy.go, cmd/ns_finder.go, cmd/push.go
This PR fixes the usage of environment name.
Previously, the CLI was using `workspace.EnvName` to perform lookups against nullstone.
When we tried the new CLI after moving to IDs, everything worked because `EnvName` still existed in the existing workspaces.
Once I tried the CLI against new workspaces, the deploy command failed because the env name was set to `""`.
=> Fix usage of environment name

cmd/app_action.go
This PR adds command context to stderr so the user can track down issues.
```
❯ nullstone launch --source=arcana --version=0.1.0 arcana dev                                                                                                                                   
Performing application command (Org=nullstone, App=arcana, Stack=, Env=dev)
Pushing app artifact...
...
```
=> Add org, app, stack, env to stderr output

app/container/aws-fargate/infra_config.go, contracts/aws-fargate-service/outputs.go, contracts/aws-fargate/outputs.go
This PR adds the deployer user to the fargate service outputs contract.
Because not all modules have been updated, this change is a forward-compatible change.
Once all usage of fargate service module is upgraded to v0.11.0+, we can drop `Deployer` user from cluster outputs.
This should be released before releasing:
- https://github.com/nullstone-modules/aws-fargate/pull/5
- https://github.com/nullstone-modules/aws-fargate-service/pull/26
=> Soft move of deployer user to fargate service

app/container/aws-ecr/provider.go, app/container/aws-fargate/infra_config.go, app/container/aws-fargate/provider.go, app/provider.go, app/server/aws-ec2/infra_config.go, app/server/aws-ec2/provider.go, app/serverless/aws-lambda/provider.go, app/static-site/aws-s3/provider.go, aws/ssm/ec2.go, aws/ssm/ecs.go, aws/ssm/plugin.go, cmd/cancellable_action.go, cmd/exec.go, contracts/aws-ec2/outputs.go, go.mod, go.sum, nullstone/main.go
This PR adds support for `server/aws-ec2` provider.
This provider falls under the `app/server` category.
Currently, this provider *only* supports the `exec` command.
Additionally, cancellation (via `SIGTERM` or `SIGINT`) was enabled for `provider.Exec`.
=> C731 ec2 ssh

CHANGELOG.md, cmd/up.go
Added `--var` to `nullstone up` allowing users to specify Terraform variable values upon launch.
This is especially helpful for the quickstarts where a `service_port` is different:
```
nullstone up --app=app --env=dev --var=service_port=8000
```
This `--var` performs light validation of the input data. Here is an example of invalid input:
```
$ nullstone up --block=test --env=dev -var=service_count=fail -var=service_cpu=x
Performing workspace command (Org=demo, Block=test, Stack=, Env=dev)
"--var" flags contain invalid values:
* service_count: expected 'number' - strconv.ParseFloat: parsing "fail": invalid syntax
* service_cpu: expected 'number' - strconv.ParseFloat: parsing "x": invalid syntax
```
=> C840 up vars

CHANGELOG.md, app/container/aws-ecr/provider.go, app/container/aws-fargate/infra_config.go, app/container/aws-fargate/provider.go, app/provider.go, app/server/aws-ec2/infra_config.go, app/server/aws-ec2/provider.go, app/serverless/aws-lambda/provider.go, app/static-site/aws-s3/provider.go, aws/ssm/ec2.go, aws/ssm/ecs.go, aws/ssm/get_document_name.go, aws/ssm/session_parameters.go, cmd/ssh.go, config/port_forward.go, go.mod, go.sum, nullstone/main.go
This adds a new command `nullstone ssh` which provides:
- SSH support for `aws-fargate` and `aws-ec2`.
- Port Forward support for `aws-ec2`.
=> `nullstone ssh`

contracts/aws-fargate-service/outputs.go, outputs/errors.go, outputs/field.go, outputs/field_test.go, outputs/mock_ns.go, outputs/retriever.go, outputs/retriever_test.go
Added `connectionContract` struct tag to outputs retriever.
This allows us to use the new module taxonomy instead of module type when extracting outputs from modules.
This is necessary since module type is no longer available in certain scenarios.
I had to fix the outputs/retriever tests that have been failing for awhile.
=> C931 contract

CHANGELOG.md, cmd/modules.go, modules/auto_version.go, modules/auto_version_test.go, outputs/field.go, outputs/retriever_test.go
Added support for `--version=auto` in `modules publish` command.
This uses the latest version and bumps the patch.
=> Auto module version

CHANGELOG.md, runs/stream_logs.go
This does the following to improve plan/apply command:
1. When using `--wait` with `plan`/`apply`, a failed run will cause the command to fail with a non-zero exit code.
2. An error message emits on failed runs pulled from `run.StatusMessage`.
=> C982 Emit non-zero exit code and error message when run fails

CHANGELOG.md, modules/package.go, workspaces/select.go
* Changed `nullstone modules publish` to include `README.md` in the package.
* Changed `nullstone workspaces select` to print specific error message if unable to initialize Terraform.
=> Add README to package, print error when unable to init terraform

CHANGELOG.md, cmd/modules.go, modules/package.go
The https://github.com/nullstone-modules/pg-db-admin module is broken after switching from curl to the nullstone CLI to perform module publish. This is because `nullstone modules publish` does not include the necessary `files/pg-db-admin.zip` in the package when publishing.
This adds an `--include` flag so that the above module can issue the following when publishing:
```
nullstone modules publish --version=<version> --include=files/pg-db-admin.zip
```
=> Added --include flag to modules publish|package commands.

CHANGELOG.md, nullstone/main.go
* CLI no longer prints `context canceled` when a user cancels a command.
=> No longer emitting "context cancelled" error when user cancels

CHANGELOG.md, aws/ssm/plugin.go
If you `nullstone ssh` to an app, then start typing a command, but want to cancel using `Cmd+C` or `Ctrl+C`, the SSH shell will exit. Then, you have to reissue `nullstone ssh`.
This fix changes the execution of AWS ssh command to trap the OS signals and forward them to the child process.
=> Forward OS signals to ssh process

CHANGELOG.md, aws/cloudwatch/log_streamer.go, aws/ecs/statuser.go, config/log_stream_options.go, display/format_time.go
Example:
```
$ nullstone status ...
Env: beta       Infra: provisioned      Version: 9dcb9e9f
Deployments
Created                  Status   Running  Desired  Pending
Fri Mar 10 16:57:12 EST  PRIMARY  1        1        0
Load Balancers
Port  Target        Status
8080  10.0.102.213  healthy
```
=> Changed display format for times to readable, local time

CHANGELOG.md, cmd/envs.go
I updated `envs new` command to sanitize input from `--name`.
This follows the same algorithm we use to create preview envs automatically.
While the user is recommended to use `<branch>-<pr_id>`, the algorithm does not enforce it.
=> Sanitizing env name in `envs new` command

CHANGELOG.md, cmd/create_deploy.go, cmd/deploy.go, cmd/flag_app_version.go, cmd/launch.go, cmd/modules.go, cmd/push.go, go.mod, go.sum, vcs/get_commit_sha.go, version/find_latest_version.go, version/find_latest_version_test.go
This PR updates the push, deploy, and launch commands to take into account whether artifacts have already been uploaded for a given commit sha. If so, a sequence number is appended on the end of the commit sha to form the version.
There were also some updates in the deployment-sdk requiring a outputs.ApiRetrieverSource. This code has been refactored to become compatible with this change.
=> F1815 deploy version

CHANGELOG.md, cmd/wait_for.go
This fixes an issue where the CLI would not stream the deploy logs after issuing `nullstone deploy`.
I suspect that there is a sporadic issue streaming websocket updates for intent workflows.
This fix attempts to improve reliability by fetching a fresh update after status transitions into `running`.
=> Refresh intent workflow to improve reliability of streaming deploy logs

cmd/apps.go, cmd/blocks.go, go.mod, go.sum, k8s/port_forwarder.go, workspaces/capabilities.go, workspaces/run_config.go
- `NamedCapabilities` was added to `WorkspaceConfig`
- `WorkspaceConfig.Capabilities` was marked for deprecation
- `WorkspaceConfig` is inlined in `RunConfig` to synchronize data structures.
- When generating capabilities terraform (`nullstone workspaces select`), we now prefer `NamedCapabilities` if it's not empty
=> This updates the CLI after adding Name to Capability

CHANGELOG.md, go.mod, go.sum
This adds the following env event actions: `env-launched`, `env-destroyed`.
In addition, this adds validation of event actions and statuses to iac files.
The `nullstone iac test` command will now report issues with event actions and statuses as well as adding support for `env-launched`, `env-destroyed`.
Relies on https://github.com/nullstone-io/iac/pull/21 and https://github.com/nullstone-io/go-api-client/pull/114
=> Added support for environment event actions (`env-launched`, `env-destroyed`)
